name: Trigger auto deployment for album-api1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-api1-AutoDeployTrigger-7fadbcab-0903-4c9c-ace9-68c895e191da.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: ca7ab7a8452bacr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI1_REGISTRY_PASSWORD }}
          containerAppName: album-api1
          resourceGroup: album-containerapps1
          imageToBuild: ca7ab7a8452bacr.azurecr.io/album-api1:${{ github.sha }}
          
            

     

