name: Trigger auto deployment for album-api60

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/album-api60-AutoDeployTrigger-93956d02-2eb9-4456-84ba-a9a7268f64f0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI60_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: caa78b81a31dacr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI60_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI60_REGISTRY_PASSWORD }}
          containerAppName: album-api60
          resourceGroup: ImpactSession-EUS
          imageToBuild: caa78b81a31dacr.azurecr.io/album-api60:${{ github.sha }}
          
            

     

